"use client";

import { useCallback, useState } from "react";

import {
  buildVeilPublicReceiptPayload,
  serializeVeilPublicReceipt,
  sha256HexUtf8,
  type VeilLedgerApiOk,
} from "@/lib/veil/veil-public-receipt";

type LedgerGet = VeilLedgerApiOk | { ok: false; message?: string };

export function AuditDisclosureExport() {
  const [msg, setMsg] = useState<string | null>(null);

  const downloadJson = useCallback(async () => {
    setMsg(null);
    try {
      const res = await fetch("/api/veil-ledger");
      const data = (await res.json()) as LedgerGet;
      if (!data.ok) {
        setMsg(data.message || "Indexer unavailable — start local devnet before exporting.");
        return;
      }
      const payload = buildVeilPublicReceiptPayload(data);
      const body = serializeVeilPublicReceipt(payload);
      const hash = await sha256HexUtf8(body);
      const disclosure = {
        veil_audit_package_version: 1,
        veil_product: "Veil",
        persona: "auditor",
        trust_boundaries: {
          indexer: "Reads follow the Midnight indexer; treat it as infrastructure you trust for this demo.",
          proof_server:
            "ZK proofs for placeholder circuits are generated by the configured proof server — not claimed as production HSM custody.",
          employer_grants:
            "Row-level salary disclosure requires an explicit employer grant and future circuits (not shipped in this slice).",
        },
        withheld_by_design: [
          "Individual employee salary rows",
          "Bank settlement and tax withholding engines",
          "Undisclosed private state from Compact witnesses",
        ],
        public_fields_allowed_today: payload.public_anchors,
        receipt_body_sha256: hash,
      };
      const text = JSON.stringify(disclosure, null, 2);
      const blob = new Blob([text], { type: "application/json;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `veil-audit-disclosure-${hash.slice(0, 8)}.json`;
      a.click();
      URL.revokeObjectURL(url);
      setMsg("Downloaded JSON disclosure package (public fields + trust framing only).");
    } catch {
      setMsg("Export failed — check that this site can reach `/api/veil-ledger`.");
    }
  }, []);

  const downloadMd = useCallback(async () => {
    setMsg(null);
    try {
      const res = await fetch("/api/veil-ledger");
      const data = (await res.json()) as LedgerGet;
      if (!data.ok) {
        setMsg(data.message || "Indexer unavailable — start local devnet before exporting.");
        return;
      }
      const payload = buildVeilPublicReceiptPayload(data);
      const body = serializeVeilPublicReceipt(payload);
      const hash = await sha256HexUtf8(body);
      const md = `# Veil auditor disclosure (demo)

## Product
${payload.veil_product} on network \`${payload.network}\` — contract \`${payload.contract_address}\`.

## Trust boundaries
- **Indexer:** public reads come from the Midnight indexer your operator runs for this demo.
- **Proof server:** builds proofs for the placeholder Compact slice; not a substitute for production key custody.
- **Employer grants:** selective disclosure of sensitive rows is intentional; missing row detail is not a broken report.

## Withheld on purpose (not bugs)
- Individual salary lines until employer-authorized disclosure circuits land.
- Bank rails, tax engines, and HRIS integrations (out of scope for this repository).

## Public anchors (allowed today)
\`\`\`json
${JSON.stringify(payload.public_anchors, null, 2)}
\`\`\`

## Receipt body hash
SHA-256 (UTF-8) of the canonical JSON receipt body: \`${hash}\`
`;
      const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `veil-audit-disclosure-${hash.slice(0, 8)}.md`;
      a.click();
      URL.revokeObjectURL(url);
      setMsg("Downloaded Markdown workpaper stub.");
    } catch {
      setMsg("Export failed — check that this site can reach `/api/veil-ledger`.");
    }
  }, []);

  return (
    <div className="mt-10 space-y-4 rounded-xl border border-(--color-edge) bg-(--color-canvas-elevated) p-6">
      <h2 className="text-sm font-medium uppercase tracking-wide text-(--color-ink-muted)">Disclosure package</h2>
      <p className="text-sm leading-relaxed text-(--color-ink-muted)">
        Export a small JSON or Markdown summary that pairs today’s public ledger fields with explicit trust boundaries.
        Individual payroll rows stay intentionally absent until selective-disclosure circuits ship.
      </p>
      <div className="flex flex-wrap gap-3">
        <button
          type="button"
          onClick={() => void downloadJson()}
          className="rounded-lg bg-(--color-accent) px-4 py-2 text-sm font-medium text-(--color-canvas) transition hover:bg-(--color-accent-hover)"
        >
          Download JSON
        </button>
        <button
          type="button"
          onClick={() => void downloadMd()}
          className="rounded-lg border border-(--color-edge) px-4 py-2 text-sm font-medium text-(--color-ink) transition hover:border-(--color-accent) hover:text-(--color-accent)"
        >
          Download Markdown
        </button>
      </div>
      {msg ? (
        <p className="text-sm text-(--color-ink-muted)" role="status">
          {msg}
        </p>
      ) : null}
    </div>
  );
}
